### ISSUE TITLE
Failure to compile with g++ 6.2.1 or clang++ 3.8

### ISSUE THREAD

**Issue by QuLogic** [Auburns/FastNoiseSIMD#5]
Firstly, #3 or some equivalent needs to be applied. Secondly, as a test, I just ran this (after commenting out the AVX2 setting):
```bash
$ for f in *.cpp; do
  echo $f
  g++ -c $f
done
```
which produces the following errors:
```
FastNoiseSIMD_avx2.cpp
FastNoiseSIMD.cpp
FastNoiseSIMD_internal.cpp
FastNoiseSIMD_sse2.cpp
FastNoiseSIMD_sse41.cpp
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h: In function ‘SIMDi_L2 L2_FUNC_Hash(const SIMDi_L2&, const SIMDi_L2&, const SIMDi_L2&, const SIMDi_L2&)’:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:514:76: note: called from here
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
                                                                            ^
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:208:39: note: called from here
 #define SIMDi_MUL(a,b) _mm_mullo_epi32(a,b)
                        ~~~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:514:9: note: in expansion of macro ‘SIMDi_MUL’
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:208:39: note: called from here
 #define SIMDi_MUL(a,b) _mm_mullo_epi32(a,b)
                        ~~~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:514:9: note: in expansion of macro ‘SIMDi_MUL’
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:244:37: note: called from here
 #define SIMDi_ADD(a,b) _mm_add_epi32(a,b)
                        ~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:512:9: note: in expansion of macro ‘SIMDi_ADD’
  hash = SIMDi_ADD(SIMDi_MUL(z, SIMDi_NUM(zPrime)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:244:37: note: called from here
 #define SIMDi_ADD(a,b) _mm_add_epi32(a,b)
                        ~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:511:9: note: in expansion of macro ‘SIMDi_ADD’
  hash = SIMDi_ADD(SIMDi_MUL(y, SIMDi_NUM(yPrime)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:244:37: note: called from here
 #define SIMDi_ADD(a,b) _mm_add_epi32(a,b)
                        ~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:510:9: note: in expansion of macro ‘SIMDi_ADD’
  hash = SIMDi_ADD(SIMDi_MUL(x, SIMDi_NUM(xPrime)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:244:37: note: called from here
 #define SIMDi_ADD(a,b) _mm_add_epi32(a,b)
                        ~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:511:9: note: in expansion of macro ‘SIMDi_ADD’
  hash = SIMDi_ADD(SIMDi_MUL(y, SIMDi_NUM(yPrime)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:244:37: note: called from here
 #define SIMDi_ADD(a,b) _mm_add_epi32(a,b)
                        ~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:512:9: note: in expansion of macro ‘SIMDi_ADD’
  hash = SIMDi_ADD(SIMDi_MUL(z, SIMDi_NUM(zPrime)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:514:76: note: called from here
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
                                                                            ^
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:208:39: note: called from here
 #define SIMDi_MUL(a,b) _mm_mullo_epi32(a,b)
                        ~~~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:514:9: note: in expansion of macro ‘SIMDi_MUL’
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
         ^~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:37:0:
/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/smmintrin.h:326:1: error: inlining failed in call to always_inline ‘__m128i _mm_mullo_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~
In file included from FastNoiseSIMD_sse41.cpp:40:0:
FastNoiseSIMD_internal.cpp:208:39: note: called from here
 #define SIMDi_MUL(a,b) _mm_mullo_epi32(a,b)
                        ~~~~~~~~~~~~~~~^~~~~
FastNoiseSIMD_internal.cpp:514:9: note: in expansion of macro ‘SIMDi_MUL’
  hash = SIMDi_MUL(SIMDi_MUL(SIMDi_MUL(hash, hash), SIMDi_NUM(60493)), hash);
         ^~~~~~~~~
```

Similar errors are reported with `clang++` 3.8 (which needs `-std=c++11`, btw) and the compiler even crashes. I am using Fedora 24 with whatever that entails; I can get specific versions of things if you need them.

**Comment by QuLogic** [comment]
`for f in *.cpp; do echo $f; g++ -march=core-avx2 -c $f; done` works for all files regardless of the AVX2 setting, so I guess `FastNoiseSIMD_sse41.cpp` also needs a note of some minimum arch as well?

**Comment by QuLogic** [comment]
For `g++`, can add `-msse4.1` (or some other suitable arch) to get that file to compile.

**Comment by QuLogic** [comment]
Same flag appears to work with `clang++`, too.

**Comment by Auburn** [comment]
For gcc and clang I use -std=c++11, and the following for individual files

- FastNoiseSIMD_sse2.cpp: -msse2
- FastNoiseSIMD_sse41.cpp: -msse4.1
- FastNoiseSIMD_avx2.cpp: -march=core-avx2

I'll make a wiki page with compiler settings so it's more clear.

**Comment by Auburn** [comment]
https://github.com/Auburns/FastNoiseSIMD/wiki/Compiler-Settings

**Comment by QuLogic** [comment]
Thanks; that's very clear now.

**Comment by QuLogic** [comment]
Can you update the wiki page for AVX512 as well?
